<?php
//邮件发送设置
$mCfg['SendMail']['Module']=1;
$mCfg['SendMail']['FromEmail']='caiyuzhuan@126.com';
$mCfg['SendMail']['FromName']='广州联雅网络科技有限公司';
$mCfg['SendMail']['Smtp']='smtp.qq.com';
$mCfg['SendMail']['Port']='25';
$mCfg['SendMail']['Email']='1607408689@163.com';
$mCfg['SendMail']['Password']='a765942a';
?>